ALTER TABLE student_profiles
ADD COLUMN points INTEGER NOT NULL DEFAULT 0,
ADD COLUMN rank_val INTEGER NOT NULL DEFAULT 0,
ADD COLUMN streak_days INTEGER NOT NULL DEFAULT 0,
ADD COLUMN level_name VARCHAR(50) NOT NULL DEFAULT 'Beginner';
