/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiLearningRouteImport } from './routes/ai-learning'
import { Route as CareerRouteImport } from './routes/career'
import { Route as CodingPracticeRouteImport } from './routes/coding-practice'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StudentRouteImport } from './routes/student'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminBatchesRouteImport } from './routes/admin.batches'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminCommunicationRouteImport } from './routes/admin.communication'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminPerformanceRouteImport } from './routes/admin.performance'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as StudentCareerRouteImport } from './routes/student.career'
import { Route as StudentCoursesRouteImport } from './routes/student.courses'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentLeaderboardRouteImport } from './routes/student.leaderboard'
import { Route as StudentLiveClassesRouteImport } from './routes/student.live-classes'
import { Route as TeacherDashboardRouteImport } from './routes/teacher.dashboard'
import { Route as TeacherStudentsRouteImport } from './routes/teacher.students'
import { Route as AdminCareerApplicationsRouteImport } from './routes/admin.career.applications'
import { Route as AdminCareerCompaniesRouteImport } from './routes/admin.career.companies'
import { Route as AdminCareerEligibilityRouteImport } from './routes/admin.career.eligibility'
import { Route as AdminCareerJobsRouteImport } from './routes/admin.career.jobs'
import { Route as AdminCareerPreparationRouteImport } from './routes/admin.career.preparation'
import { Route as AdminCareerReferralsRouteImport } from './routes/admin.career.referrals'
import { Route as AdminCareerResourcesRouteImport } from './routes/admin.career.resources'
import { Route as AdminCareerResumeTemplatesRouteImport } from './routes/admin.career.resume-templates'
import { Route as AdminCrmIndexRouteImport } from './routes/admin.crm.index'
import { Route as AdminCrmLeadIdRouteImport } from './routes/admin.crm.$leadId'
import { Route as AdminMarketingCouponsRouteImport } from './routes/admin.marketing.coupons'
import { Route as AdminStudentsIndexRouteImport } from './routes/admin.students.index'
import { Route as AdminStudentsStudentIdRouteImport } from './routes/admin.students.$studentId'
import { Route as StudentCareerIndexRouteImport } from './routes/student.career.index'
import { Route as StudentCareerApplicationsRouteImport } from './routes/student.career.applications'
import { Route as StudentCareerJobsRouteImport } from './routes/student.career.jobs'
import { Route as StudentCareerOnboardingRouteImport } from './routes/student.career.onboarding'
import { Route as StudentCareerProfileRouteImport } from './routes/student.career.profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiLearningRoute = AiLearningRouteImport.update({
  id: '/ai-learning',
  path: '/ai-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const CodingPracticeRoute = CodingPracticeRouteImport.update({
  id: '/coding-practice',
  path: '/coding-practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBatchesRoute = AdminBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunicationRoute = AdminCommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerformanceRoute = AdminPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCareerRoute = StudentCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLeaderboardRoute = StudentLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLiveClassesRoute = StudentLiveClassesRouteImport.update({
  id: '/live-classes',
  path: '/live-classes',
  getParentRoute: () => StudentRoute,
} as any)
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TeacherRoute,
} as any)
const AdminCareerApplicationsRoute = AdminCareerApplicationsRouteImport.update({
  id: '/career/applications',
  path: '/career/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCareerCompaniesRoute = AdminCareerCompaniesRouteImport.update({
  id: '/career/companies',
  path: '/career/companies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCareerEligibilityRoute = AdminCareerEligibilityRouteImport.update({
  id: '/career/eligibility',
  path: '/career/eligibility',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCareerJobsRoute = AdminCareerJobsRouteImport.update({
  id: '/career/jobs',
  path: '/career/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCareerPreparationRoute = AdminCareerPreparationRouteImport.update({
  id: '/career/preparation',
  path: '/career/preparation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCareerReferralsRoute = AdminCareerReferralsRouteImport.update({
  id: '/career/referrals',
  path: '/career/referrals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCareerResourcesRoute = AdminCareerResourcesRouteImport.update({
  id: '/career/resources',
  path: '/career/resources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCareerResumeTemplatesRoute =
  AdminCareerResumeTemplatesRouteImport.update({
    id: '/career/resume-templates',
    path: '/career/resume-templates',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCrmIndexRoute = AdminCrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrmLeadIdRoute = AdminCrmLeadIdRouteImport.update({
  id: '/crm/$leadId',
  path: '/crm/$leadId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingCouponsRoute = AdminMarketingCouponsRouteImport.update({
  id: '/marketing/coupons',
  path: '/marketing/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsIndexRoute = AdminStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsStudentIdRoute = AdminStudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => AdminRoute,
} as any)
const StudentCareerIndexRoute = StudentCareerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentCareerRoute,
} as any)
const StudentCareerApplicationsRoute =
  StudentCareerApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => StudentCareerRoute,
  } as any)
const StudentCareerJobsRoute = StudentCareerJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => StudentCareerRoute,
} as any)
const StudentCareerOnboardingRoute = StudentCareerOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => StudentCareerRoute,
} as any)
const StudentCareerProfileRoute = StudentCareerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentCareerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-learning': typeof AiLearningRoute
  '/career': typeof CareerRoute
  '/coding-practice': typeof CodingPracticeRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/programs': typeof ProgramsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/student/career': typeof StudentCareerRouteWithChildren
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/live-classes': typeof StudentLiveClassesRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/career/applications': typeof AdminCareerApplicationsRoute
  '/admin/career/companies': typeof AdminCareerCompaniesRoute
  '/admin/career/eligibility': typeof AdminCareerEligibilityRoute
  '/admin/career/jobs': typeof AdminCareerJobsRoute
  '/admin/career/preparation': typeof AdminCareerPreparationRoute
  '/admin/career/referrals': typeof AdminCareerReferralsRoute
  '/admin/career/resources': typeof AdminCareerResourcesRoute
  '/admin/career/resume-templates': typeof AdminCareerResumeTemplatesRoute
  '/admin/crm/$leadId': typeof AdminCrmLeadIdRoute
  '/admin/marketing/coupons': typeof AdminMarketingCouponsRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdRoute
  '/student/career/applications': typeof StudentCareerApplicationsRoute
  '/student/career/jobs': typeof StudentCareerJobsRoute
  '/student/career/onboarding': typeof StudentCareerOnboardingRoute
  '/student/career/profile': typeof StudentCareerProfileRoute
  '/admin/crm/': typeof AdminCrmIndexRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/student/career/': typeof StudentCareerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-learning': typeof AiLearningRoute
  '/career': typeof CareerRoute
  '/coding-practice': typeof CodingPracticeRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/programs': typeof ProgramsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/live-classes': typeof StudentLiveClassesRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/courses': typeof CoursesIndexRoute
  '/admin/career/applications': typeof AdminCareerApplicationsRoute
  '/admin/career/companies': typeof AdminCareerCompaniesRoute
  '/admin/career/eligibility': typeof AdminCareerEligibilityRoute
  '/admin/career/jobs': typeof AdminCareerJobsRoute
  '/admin/career/preparation': typeof AdminCareerPreparationRoute
  '/admin/career/referrals': typeof AdminCareerReferralsRoute
  '/admin/career/resources': typeof AdminCareerResourcesRoute
  '/admin/career/resume-templates': typeof AdminCareerResumeTemplatesRoute
  '/admin/crm/$leadId': typeof AdminCrmLeadIdRoute
  '/admin/marketing/coupons': typeof AdminMarketingCouponsRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdRoute
  '/student/career/applications': typeof StudentCareerApplicationsRoute
  '/student/career/jobs': typeof StudentCareerJobsRoute
  '/student/career/onboarding': typeof StudentCareerOnboardingRoute
  '/student/career/profile': typeof StudentCareerProfileRoute
  '/admin/crm': typeof AdminCrmIndexRoute
  '/admin/students': typeof AdminStudentsIndexRoute
  '/student/career': typeof StudentCareerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-learning': typeof AiLearningRoute
  '/career': typeof CareerRoute
  '/coding-practice': typeof CodingPracticeRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/programs': typeof ProgramsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/student/career': typeof StudentCareerRouteWithChildren
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/live-classes': typeof StudentLiveClassesRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/career/applications': typeof AdminCareerApplicationsRoute
  '/admin/career/companies': typeof AdminCareerCompaniesRoute
  '/admin/career/eligibility': typeof AdminCareerEligibilityRoute
  '/admin/career/jobs': typeof AdminCareerJobsRoute
  '/admin/career/preparation': typeof AdminCareerPreparationRoute
  '/admin/career/referrals': typeof AdminCareerReferralsRoute
  '/admin/career/resources': typeof AdminCareerResourcesRoute
  '/admin/career/resume-templates': typeof AdminCareerResumeTemplatesRoute
  '/admin/crm/$leadId': typeof AdminCrmLeadIdRoute
  '/admin/marketing/coupons': typeof AdminMarketingCouponsRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdRoute
  '/student/career/applications': typeof StudentCareerApplicationsRoute
  '/student/career/jobs': typeof StudentCareerJobsRoute
  '/student/career/onboarding': typeof StudentCareerOnboardingRoute
  '/student/career/profile': typeof StudentCareerProfileRoute
  '/admin/crm/': typeof AdminCrmIndexRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/student/career/': typeof StudentCareerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ai-learning'
    | '/career'
    | '/coding-practice'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/programs'
    | '/register'
    | '/reset-password'
    | '/student'
    | '/teacher'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/articles'
    | '/admin/attendance'
    | '/admin/audit-logs'
    | '/admin/batches'
    | '/admin/cms'
    | '/admin/communication'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/notifications'
    | '/admin/performance'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/teachers'
    | '/courses/$slug'
    | '/student/career'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/leaderboard'
    | '/student/live-classes'
    | '/teacher/dashboard'
    | '/teacher/students'
    | '/courses/'
    | '/admin/career/applications'
    | '/admin/career/companies'
    | '/admin/career/eligibility'
    | '/admin/career/jobs'
    | '/admin/career/preparation'
    | '/admin/career/referrals'
    | '/admin/career/resources'
    | '/admin/career/resume-templates'
    | '/admin/crm/$leadId'
    | '/admin/marketing/coupons'
    | '/admin/students/$studentId'
    | '/student/career/applications'
    | '/student/career/jobs'
    | '/student/career/onboarding'
    | '/student/career/profile'
    | '/admin/crm/'
    | '/admin/students/'
    | '/student/career/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/ai-learning'
    | '/career'
    | '/coding-practice'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/programs'
    | '/register'
    | '/reset-password'
    | '/student'
    | '/teacher'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/articles'
    | '/admin/attendance'
    | '/admin/audit-logs'
    | '/admin/batches'
    | '/admin/cms'
    | '/admin/communication'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/notifications'
    | '/admin/performance'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/teachers'
    | '/courses/$slug'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/leaderboard'
    | '/student/live-classes'
    | '/teacher/dashboard'
    | '/teacher/students'
    | '/courses'
    | '/admin/career/applications'
    | '/admin/career/companies'
    | '/admin/career/eligibility'
    | '/admin/career/jobs'
    | '/admin/career/preparation'
    | '/admin/career/referrals'
    | '/admin/career/resources'
    | '/admin/career/resume-templates'
    | '/admin/crm/$leadId'
    | '/admin/marketing/coupons'
    | '/admin/students/$studentId'
    | '/student/career/applications'
    | '/student/career/jobs'
    | '/student/career/onboarding'
    | '/student/career/profile'
    | '/admin/crm'
    | '/admin/students'
    | '/student/career'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ai-learning'
    | '/career'
    | '/coding-practice'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/programs'
    | '/register'
    | '/reset-password'
    | '/student'
    | '/teacher'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/articles'
    | '/admin/attendance'
    | '/admin/audit-logs'
    | '/admin/batches'
    | '/admin/cms'
    | '/admin/communication'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/notifications'
    | '/admin/performance'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/teachers'
    | '/courses/$slug'
    | '/student/career'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/leaderboard'
    | '/student/live-classes'
    | '/teacher/dashboard'
    | '/teacher/students'
    | '/courses/'
    | '/admin/career/applications'
    | '/admin/career/companies'
    | '/admin/career/eligibility'
    | '/admin/career/jobs'
    | '/admin/career/preparation'
    | '/admin/career/referrals'
    | '/admin/career/resources'
    | '/admin/career/resume-templates'
    | '/admin/crm/$leadId'
    | '/admin/marketing/coupons'
    | '/admin/students/$studentId'
    | '/student/career/applications'
    | '/student/career/jobs'
    | '/student/career/onboarding'
    | '/student/career/profile'
    | '/admin/crm/'
    | '/admin/students/'
    | '/student/career/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiLearningRoute: typeof AiLearningRoute
  CareerRoute: typeof CareerRoute
  CodingPracticeRoute: typeof CodingPracticeRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProgramsRoute: typeof ProgramsRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-learning': {
      id: '/ai-learning'
      path: '/ai-learning'
      fullPath: '/ai-learning'
      preLoaderRoute: typeof AiLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coding-practice': {
      id: '/coding-practice'
      path: '/coding-practice'
      fullPath: '/coding-practice'
      preLoaderRoute: typeof CodingPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/batches': {
      id: '/admin/batches'
      path: '/batches'
      fullPath: '/admin/batches'
      preLoaderRoute: typeof AdminBatchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communication': {
      id: '/admin/communication'
      path: '/communication'
      fullPath: '/admin/communication'
      preLoaderRoute: typeof AdminCommunicationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/performance': {
      id: '/admin/performance'
      path: '/performance'
      fullPath: '/admin/performance'
      preLoaderRoute: typeof AdminPerformanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/career': {
      id: '/student/career'
      path: '/career'
      fullPath: '/student/career'
      preLoaderRoute: typeof StudentCareerRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/leaderboard': {
      id: '/student/leaderboard'
      path: '/leaderboard'
      fullPath: '/student/leaderboard'
      preLoaderRoute: typeof StudentLeaderboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/live-classes': {
      id: '/student/live-classes'
      path: '/live-classes'
      fullPath: '/student/live-classes'
      preLoaderRoute: typeof StudentLiveClassesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/teacher/dashboard': {
      id: '/teacher/dashboard'
      path: '/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/admin/career/applications': {
      id: '/admin/career/applications'
      path: '/career/applications'
      fullPath: '/admin/career/applications'
      preLoaderRoute: typeof AdminCareerApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/career/companies': {
      id: '/admin/career/companies'
      path: '/career/companies'
      fullPath: '/admin/career/companies'
      preLoaderRoute: typeof AdminCareerCompaniesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/career/eligibility': {
      id: '/admin/career/eligibility'
      path: '/career/eligibility'
      fullPath: '/admin/career/eligibility'
      preLoaderRoute: typeof AdminCareerEligibilityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/career/jobs': {
      id: '/admin/career/jobs'
      path: '/career/jobs'
      fullPath: '/admin/career/jobs'
      preLoaderRoute: typeof AdminCareerJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/career/preparation': {
      id: '/admin/career/preparation'
      path: '/career/preparation'
      fullPath: '/admin/career/preparation'
      preLoaderRoute: typeof AdminCareerPreparationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/career/referrals': {
      id: '/admin/career/referrals'
      path: '/career/referrals'
      fullPath: '/admin/career/referrals'
      preLoaderRoute: typeof AdminCareerReferralsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/career/resources': {
      id: '/admin/career/resources'
      path: '/career/resources'
      fullPath: '/admin/career/resources'
      preLoaderRoute: typeof AdminCareerResourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/career/resume-templates': {
      id: '/admin/career/resume-templates'
      path: '/career/resume-templates'
      fullPath: '/admin/career/resume-templates'
      preLoaderRoute: typeof AdminCareerResumeTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crm/': {
      id: '/admin/crm/'
      path: '/crm'
      fullPath: '/admin/crm/'
      preLoaderRoute: typeof AdminCrmIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crm/$leadId': {
      id: '/admin/crm/$leadId'
      path: '/crm/$leadId'
      fullPath: '/admin/crm/$leadId'
      preLoaderRoute: typeof AdminCrmLeadIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/coupons': {
      id: '/admin/marketing/coupons'
      path: '/marketing/coupons'
      fullPath: '/admin/marketing/coupons'
      preLoaderRoute: typeof AdminMarketingCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/': {
      id: '/admin/students/'
      path: '/students'
      fullPath: '/admin/students/'
      preLoaderRoute: typeof AdminStudentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/$studentId': {
      id: '/admin/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/admin/students/$studentId'
      preLoaderRoute: typeof AdminStudentsStudentIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/career/': {
      id: '/student/career/'
      path: '/'
      fullPath: '/student/career/'
      preLoaderRoute: typeof StudentCareerIndexRouteImport
      parentRoute: typeof StudentCareerRoute
    }
    '/student/career/applications': {
      id: '/student/career/applications'
      path: '/applications'
      fullPath: '/student/career/applications'
      preLoaderRoute: typeof StudentCareerApplicationsRouteImport
      parentRoute: typeof StudentCareerRoute
    }
    '/student/career/jobs': {
      id: '/student/career/jobs'
      path: '/jobs'
      fullPath: '/student/career/jobs'
      preLoaderRoute: typeof StudentCareerJobsRouteImport
      parentRoute: typeof StudentCareerRoute
    }
    '/student/career/onboarding': {
      id: '/student/career/onboarding'
      path: '/onboarding'
      fullPath: '/student/career/onboarding'
      preLoaderRoute: typeof StudentCareerOnboardingRouteImport
      parentRoute: typeof StudentCareerRoute
    }
    '/student/career/profile': {
      id: '/student/career/profile'
      path: '/profile'
      fullPath: '/student/career/profile'
      preLoaderRoute: typeof StudentCareerProfileRouteImport
      parentRoute: typeof StudentCareerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminBatchesRoute: typeof AdminBatchesRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminCommunicationRoute: typeof AdminCommunicationRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPerformanceRoute: typeof AdminPerformanceRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminCareerApplicationsRoute: typeof AdminCareerApplicationsRoute
  AdminCareerCompaniesRoute: typeof AdminCareerCompaniesRoute
  AdminCareerEligibilityRoute: typeof AdminCareerEligibilityRoute
  AdminCareerJobsRoute: typeof AdminCareerJobsRoute
  AdminCareerPreparationRoute: typeof AdminCareerPreparationRoute
  AdminCareerReferralsRoute: typeof AdminCareerReferralsRoute
  AdminCareerResourcesRoute: typeof AdminCareerResourcesRoute
  AdminCareerResumeTemplatesRoute: typeof AdminCareerResumeTemplatesRoute
  AdminCrmLeadIdRoute: typeof AdminCrmLeadIdRoute
  AdminMarketingCouponsRoute: typeof AdminMarketingCouponsRoute
  AdminStudentsStudentIdRoute: typeof AdminStudentsStudentIdRoute
  AdminCrmIndexRoute: typeof AdminCrmIndexRoute
  AdminStudentsIndexRoute: typeof AdminStudentsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminArticlesRoute: AdminArticlesRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminBatchesRoute: AdminBatchesRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminCommunicationRoute: AdminCommunicationRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPerformanceRoute: AdminPerformanceRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminCareerApplicationsRoute: AdminCareerApplicationsRoute,
  AdminCareerCompaniesRoute: AdminCareerCompaniesRoute,
  AdminCareerEligibilityRoute: AdminCareerEligibilityRoute,
  AdminCareerJobsRoute: AdminCareerJobsRoute,
  AdminCareerPreparationRoute: AdminCareerPreparationRoute,
  AdminCareerReferralsRoute: AdminCareerReferralsRoute,
  AdminCareerResourcesRoute: AdminCareerResourcesRoute,
  AdminCareerResumeTemplatesRoute: AdminCareerResumeTemplatesRoute,
  AdminCrmLeadIdRoute: AdminCrmLeadIdRoute,
  AdminMarketingCouponsRoute: AdminMarketingCouponsRoute,
  AdminStudentsStudentIdRoute: AdminStudentsStudentIdRoute,
  AdminCrmIndexRoute: AdminCrmIndexRoute,
  AdminStudentsIndexRoute: AdminStudentsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentCareerRouteChildren {
  StudentCareerApplicationsRoute: typeof StudentCareerApplicationsRoute
  StudentCareerJobsRoute: typeof StudentCareerJobsRoute
  StudentCareerOnboardingRoute: typeof StudentCareerOnboardingRoute
  StudentCareerProfileRoute: typeof StudentCareerProfileRoute
  StudentCareerIndexRoute: typeof StudentCareerIndexRoute
}

const StudentCareerRouteChildren: StudentCareerRouteChildren = {
  StudentCareerApplicationsRoute: StudentCareerApplicationsRoute,
  StudentCareerJobsRoute: StudentCareerJobsRoute,
  StudentCareerOnboardingRoute: StudentCareerOnboardingRoute,
  StudentCareerProfileRoute: StudentCareerProfileRoute,
  StudentCareerIndexRoute: StudentCareerIndexRoute,
}

const StudentCareerRouteWithChildren = StudentCareerRoute._addFileChildren(
  StudentCareerRouteChildren,
)

interface StudentRouteChildren {
  StudentCareerRoute: typeof StudentCareerRouteWithChildren
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentLeaderboardRoute: typeof StudentLeaderboardRoute
  StudentLiveClassesRoute: typeof StudentLiveClassesRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCareerRoute: StudentCareerRouteWithChildren,
  StudentCoursesRoute: StudentCoursesRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentLeaderboardRoute: StudentLeaderboardRoute,
  StudentLiveClassesRoute: StudentLiveClassesRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherDashboardRoute: typeof TeacherDashboardRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherDashboardRoute: TeacherDashboardRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AiLearningRoute: AiLearningRoute,
  CareerRoute: CareerRoute,
  CodingPracticeRoute: CodingPracticeRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProgramsRoute: ProgramsRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
